### ISSUE TITLE
More of a question then a bug, But does this fix the issue where YouTube links don't open up in the side-loaded version of YouTube?

### ISSUE THREAD

**Issue by atebitsy** [PoomSmart/IAmYouTube#2]
More of a question then a bug, But does this fix the issue where YouTube links don't open up in the side-loaded version of YouTube? Thank you, for taking time to read this :)

**Comment by PoomSmart** [comment]
Bundle identifier checks (that this tweak hooks) serve multiple purposes. Some apps (YouTube included) does it for functionalities (for example, check if itself is a developer build). Some apps does it for integrity (so that it won't run in the "contaminated" self). Some apps does it for analytics.

There are a set of issues that this tweak can never fix in jailed mode. Check this answer by our fellow kabiroberai dev:

![image](https://user-images.githubusercontent.com/3608783/127588899-caa04800-27eb-491c-9a9d-162fc21b92f0.png)
